spring:
  config:
    import: optional:file:.env
  application:
    name: Inventory System Manager for Online Store
  datasource:
    url: jdbc:postgresql://${POSTGRE_HOST}:${POSTGRE_PORT}/${POSTGRE_DATABASENAME}
    username: ${POSTGRE_USER}
    password: ${POSTGRE_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  rabbitmq:
    host: ${RABBITMQ_HOST}
    port: ${RABBITMQ_PORT}
    username: ${RABBITMQ_USER}
    password: ${RABBITMQ_PASSWORD}

jwtKey: ${JWT_SECRET_KEY}
